import type { ThreadOperationalFlags, UnifiedTimelineEntry } from "../entities";

export const DEFAULT_THREAD_FLAGS: ThreadOperationalFlags = {
  paymentRisk: false,
  recoveryActive: false,
  humanTakeover: false,
  vipEscalation: false,
  otaConversion: false,
  memoryAttached: false,
  priorRiskDetected: false,
  vipHistory: false,
  directBookingCandidate: false,
};

export const SEED_UNIFIED_TIMELINE: UnifiedTimelineEntry[] = [
  {
    id: "tl-seed-1",
    kind: "PAYMENT_FAILED",
    title: "Üç Kişilik Oda için ödeme riski algılandı",
    detail: "Etki: gelir · rezervasyon · kurtarma · hafıza",
    timestamp: "11:24",
    actor: "system",
    guestId: "g2",
    guestLabel: "Hans Mueller",
    reservationId: "or2",
    conversationId: "c2",
    financialImpactEur: 780,
    propagationNodes: ["revenue", "reservation", "recovery", "memory", "timeline"],
  },
  {
    id: "tl-seed-2",
    kind: "VIP_ESCALATION",
    title: "VIP yükseltme · operatör devraldı",
    detail: "Etki: görüşme · misafir zekası · denetim · uyarılar",
    timestamp: "08:42",
    actor: "ai",
    guestId: "g1",
    guestLabel: "Elena Petrov",
    conversationId: "c3",
    financialImpactEur: 2180,
    propagationNodes: ["thread", "guest", "alert", "audit", "memory"],
  },
  {
    id: "tl-seed-3",
    kind: "OTA_CONVERSION",
    title: "OTA → direkt rezervasyon dönüşümü sağlandı",
    detail: "Komisyon önlendi · sadakat hafızası güncellendi",
    timestamp: "09:19",
    actor: "ai",
    guestId: "g3",
    guestLabel: "Sophie Martin",
    financialImpactEur: 212,
    propagationNodes: ["revenue", "guest", "recovery", "timeline"],
  },
  {
    id: "tl-seed-4",
    kind: "UPSELL_ACCEPTED",
    title: "Onay sonrası ek satış kabul edildi",
    detail: "ADR artışı · misafir finansal hafızası zenginleşti",
    timestamp: "10:02",
    actor: "ai",
    guestId: "g4",
    guestLabel: "Sarah Johnson",
    reservationId: "or1",
    financialImpactEur: 95,
    propagationNodes: ["revenue", "reservation", "guest", "timeline"],
  },
];
