import type { OperationalState } from "../entities";
import { withGuestGraphDefaults } from "../graph/memory";
import { DEFAULT_THREAD_FLAGS, SEED_UNIFIED_TIMELINE } from "./graph-seed";

const RAW_OPERATIONAL_STATE = {
  mounted: false,
  revenue: {
    revenueRecoveredToday: 4280,
    aiInfluencedRevenue: 12400,
    otaCommissionAvoided: 1860,
    upsellRevenueGenerated: 720,
    paymentRecoveryRevenue: 2180,
    humanTakeoverSavedRevenue: 1450,
    revenueAtRisk: 3120,
    recoverySuccessRate: 78,
    directBookingConversionValue: 5400,
    aiGeneratedRevenue: 8920,
    escalatedRevenueExposure: 1980,
    occupancyInfluencePct: 4.2,
  },
  aiImpact: {
    aiCloseRate: 34,
    aiAssistedRecoveryRate: 72,
    autonomousResolutionPct: 68,
    humanTakeoverSuccessPct: 91,
    escalationPreventionPct: 63,
    revenueInfluencedByAi: 12400,
    aiConfidenceStability: 87,
    guestRecoveryRate: 74,
    confidenceTrend: [82, 84, 83, 86, 85, 87, 87],
  },
  ota: {
    otaLeakagePct: 22,
    directConversionRate: 18,
    recoveredCommissionSavings: 1860,
    loyaltyConversions: 4,
    activeRecoveryWorkflows: 2,
  },
  activeRecoveries: [
    {
      id: "rj1",
      kind: "failed_payment",
      guestLabel: "Hans Mueller",
      roomLabel: "Üç Kişilik Oda · 28 Haz–3 Tem",
      status: "active",
      bookingValueEur: 780,
      revenueSavedEur: 0,
      reservationId: "or2",
      conversationId: "c2",
      aiRationale:
        "Ödeme sorunu algılandı — AI politika dahilinde alternatif bağlantı ve depozito bölme önerdi.",
      steps: [
        {
          id: "s1",
          phase: "risk",
          title: "Ödeme riski algılandı",
          detail: "Kart reddedildi · €780 risk altında",
          timestamp: "11:24",
          revenueDeltaEur: -780,
        },
        {
          id: "s2",
          phase: "ai_intervention",
          title: "AI ödeme kurtarma akışı",
          detail: "Alternatif ödeme bağlantısı + politika açıklaması",
          timestamp: "11:25",
        },
        {
          id: "s3",
          phase: "escalation",
          title: "Operasyon bilgilendirildi",
          detail: "Vardiya yöneticisi hazır · SLA 12 dk",
          timestamp: "11:26",
        },
      ],
    },
    {
      id: "rj2",
      kind: "ota_to_direct",
      guestLabel: "Sophie Martin",
      roomLabel: "Superior Çift Kişilik Oda · 2–6 Ağu",
      status: "recovered",
      bookingValueEur: 1180,
      revenueSavedEur: 212,
      aiRationale: "OTA kaynaklı misafire direkt fiyat eşlemesi önerildi — kapanışta komisyon önlendi.",
      steps: [
        {
          id: "s1",
          phase: "risk",
          title: "OTA kaybı işaretlendi",
          detail: "Booking.com talebi · %18 komisyon riski",
          timestamp: "09:02",
          revenueDeltaEur: -212,
        },
        {
          id: "s2",
          phase: "ai_intervention",
          title: "Direkt dönüşüm akışı",
          detail: "Fiyat eşitliği + sadakat avantajı öne çıkarıldı",
          timestamp: "09:04",
        },
        {
          id: "s3",
          phase: "recovery",
          title: "Direkt rezervasyon alındı",
          detail: "Misafir güvenli ödeme bağlantısını kabul etti",
          timestamp: "09:18",
          revenueDeltaEur: 1180,
        },
        {
          id: "s4",
          phase: "confirmation",
          title: "Komisyon önlendi",
          detail: "€212 OTA komisyonu içeride kaldı",
          timestamp: "09:19",
          revenueDeltaEur: 212,
        },
      ],
    },
    {
      id: "rj3",
      kind: "takeover_rescue",
      guestLabel: "Elena Petrov",
      roomLabel: "Deluxe Suite · 12–15 Ağu",
      status: "recovered",
      bookingValueEur: 2180,
      revenueSavedEur: 2180,
      aiRationale:
        "VIP politika sınırı — AI bağlamı korunarak operatör devri iptali önledi.",
      steps: [
        {
          id: "s1",
          phase: "risk",
          title: "İptal riski",
          detail: "Politika anlaşmazlığı · Rusça görüşme · skor 0.88",
          timestamp: "08:41",
          revenueDeltaEur: -2180,
        },
        {
          id: "s2",
          phase: "ai_intervention",
          title: "AI ön değerlendirme + yükseltme",
          detail: "Devralma önerildi · bağlam paketi gönderildi",
          timestamp: "08:42",
        },
        {
          id: "s3",
          phase: "escalation",
          title: "Operatör devraldı",
          detail: "Maria L. katıldı · politika istisnası hazırlandı",
          timestamp: "08:44",
        },
        {
          id: "s4",
          phase: "confirmation",
          title: "Rezervasyon kurtarıldı",
          detail: "VIP misafir korundu · €2.180 güvenceye alındı",
          timestamp: "08:52",
          revenueDeltaEur: 2180,
        },
      ],
    },
  ],
  revenueEvents: [
    {
      id: "st1",
      headline: "AI ödeme sorunundan sonra €2.180 rezervasyonu kurtardı",
      narrative: "VIP görüşme tam bağlamla yükseltildi — operatör müdahalesi 8 dakika içinde kapattı.",
      amountEur: 2180,
      attribution: "payment_recovery",
      timestamp: "08:52",
      conversationId: "c3",
      reservationId: "r-vip-1",
    },
    {
      id: "st2",
      headline: "Operatör devri VIP iptalini önledi",
      narrative: "Politika sınır durumu — AI devralma önerdi; gelir riski kapatıldı.",
      amountEur: 2180,
      attribution: "vip_intervention",
      timestamp: "08:52",
      conversationId: "c3",
    },
    {
      id: "st3",
      headline: "OTA kurtarma akışı %18 komisyonu korudu",
      narrative: "Superior oda direkt rezervasyona dönüştü — komisyon içeride kaldı.",
      amountEur: 212,
      attribution: "ota_commission",
      timestamp: "09:19",
      reservationId: "r-ota-1",
    },
    {
      id: "st4",
      headline: "AI ek satışla €120 ilave ADR oluşturdu",
      narrative: "Geç çıkış + kahvaltı paketi onay sonrası kabul edildi.",
      amountEur: 120,
      attribution: "ai_upsell",
      timestamp: "Dün",
      reservationId: "or1",
    },
  ],
  reservations: [
    {
      id: "or1",
      guest: "Sarah Johnson",
      initials: "SJ",
      room: "Deluxe Suite",
      checkIn: "15 Haz",
      checkOut: "20 Haz",
      guests: 2,
      nights: 5,
      currentStage: "confirmation",
      bookingValueEur: 850,
      revenueAtRiskEur: 0,
      channel: "Direkt · WhatsApp",
      conversationId: "c4",
      attributions: [
        {
          kind: "direct_conversion",
          label: "Direkt kapanış",
          amountEur: 850,
          aiContributed: true,
          detail: "AI nitelendirdi + teklifledi",
        },
      ],
      timeline: [
        { stage: "inquiry", label: "Talep alındı", timestamp: "09:12", actor: "guest" },
        {
          stage: "quote",
          label: "Teklif gönderildi",
          timestamp: "09:18",
          financialImpactEur: 850,
          actor: "ai",
        },
        { stage: "payment_pending", label: "Ödeme bağlantısı gönderildi", timestamp: "09:22", actor: "ai" },
        {
          stage: "confirmation",
          label: "Onaylandı",
          timestamp: "09:41",
          financialImpactEur: 850,
          actor: "system",
        },
        {
          stage: "upsell",
          label: "Ek satış kabul edildi",
          timestamp: "10:02",
          financialImpactEur: 95,
          actor: "ai",
          note: "ADR +€95",
        },
      ],
    },
    {
      id: "or2",
      guest: "Hans Mueller",
      initials: "HM",
      room: "Üç Kişilik Oda",
      checkIn: "28 Haz",
      checkOut: "3 Tem",
      guests: 3,
      nights: 5,
      currentStage: "payment_risk",
      bookingValueEur: 780,
      revenueAtRiskEur: 780,
      channel: "Direkt · WhatsApp",
      conversationId: "c2",
      attributions: [
        {
          kind: "payment_recovery",
          label: "Kurtarma devam ediyor",
          amountEur: 780,
          aiContributed: true,
          detail: "Alternatif bağlantı gönderildi",
        },
      ],
      timeline: [
        { stage: "inquiry", label: "Talep", timestamp: "10:45", actor: "guest" },
        { stage: "quote", label: "Teklif gönderildi", timestamp: "11:02", financialImpactEur: 780, actor: "ai" },
        { stage: "payment_pending", label: "Ödeme bekleniyor", timestamp: "11:10", actor: "ai" },
        {
          stage: "payment_risk",
          label: "Ödeme başarısız",
          timestamp: "11:24",
          financialImpactEur: -780,
          actor: "system",
        },
        { stage: "recovery", label: "AI kurtarma aktif", timestamp: "11:25", actor: "ai" },
      ],
    },
    {
      id: "or3",
      guest: "Mohammed Al-Said",
      initials: "MS",
      room: "Aile Odası",
      checkIn: "1 Tem",
      checkOut: "7 Tem",
      guests: 4,
      nights: 6,
      currentStage: "retention",
      bookingValueEur: 1200,
      revenueAtRiskEur: 0,
      channel: "Direkt · Web",
      attributions: [
        { kind: "direct_conversion", label: "Direkt rezervasyon", amountEur: 1200, aiContributed: true },
        {
          kind: "ota_commission",
          label: "OTA önlendi (tahmini)",
          amountEur: 216,
          aiContributed: true,
          detail: "18% commission",
        },
      ],
      timeline: [
        { stage: "inquiry", label: "Web talebi", timestamp: "Dün", actor: "guest" },
        {
          stage: "confirmation",
          label: "Onaylandı",
          timestamp: "Dün",
          financialImpactEur: 1200,
          actor: "ai",
        },
        { stage: "retention", label: "Varış öncesi takip", timestamp: "Bugün", actor: "ai" },
      ],
    },
    {
      id: "or4",
      guest: "Giulia Romano",
      initials: "GR",
      room: "Çift Kişilik Oda",
      checkIn: "10 Tem",
      checkOut: "15 Tem",
      guests: 2,
      nights: 5,
      currentStage: "confirmation",
      bookingValueEur: 650,
      revenueAtRiskEur: 0,
      channel: "Instagram → Direkt",
      attributions: [
        {
          kind: "abandoned_recovery",
          label: "Yarım kalan rezervasyon kurtarıldı",
          amountEur: 650,
          aiContributed: true,
        },
      ],
      timeline: [
        { stage: "quote", label: "Teklif yanıt bekliyor", timestamp: "10:08", actor: "guest" },
        { stage: "recovery", label: "AI yeniden temas", timestamp: "10:55", actor: "ai" },
        {
          stage: "confirmation",
          label: "Kurtarıldı",
          timestamp: "11:14",
          financialImpactEur: 650,
          actor: "system",
        },
      ],
    },
  ],
  guests: [
    {
      id: "g1",
      name: "Elena Petrov",
      initials: "EP",
      avatarColor: "bg-rose-600",
      segment: "vip",
      lifetimeValueEur: 4200,
      aiInfluencedRevenueEur: 2180,
      recoveryCount: 1,
      vipRescueCount: 1,
      otaConversionCount: 0,
      lastAttribution: {
        kind: "vip_intervention",
          label: "VIP kurtarma",
        amountEur: 2180,
        aiContributed: true,
      },
      conversationId: "c3",
    },
    {
      id: "g2",
      name: "Hans Mueller",
      initials: "HM",
      avatarColor: "bg-blue-600",
      segment: "standard",
      lifetimeValueEur: 1560,
      aiInfluencedRevenueEur: 780,
      recoveryCount: 0,
      vipRescueCount: 0,
      otaConversionCount: 0,
      lastAttribution: {
        kind: "payment_recovery",
          label: "Ödeme kurtarma",
        amountEur: 780,
        aiContributed: true,
      },
      conversationId: "c2",
    },
    {
      id: "g3",
      name: "Sophie Martin",
      initials: "SM",
      avatarColor: "bg-violet-600",
      segment: "ota_origin",
      lifetimeValueEur: 2400,
      aiInfluencedRevenueEur: 1180,
      recoveryCount: 1,
      vipRescueCount: 0,
      otaConversionCount: 1,
      lastAttribution: {
        kind: "ota_commission",
          label: "OTA → direkt",
        amountEur: 212,
        aiContributed: true,
      },
      conversationId: "c-ota",
    },
    {
      id: "g4",
      name: "Sarah Johnson",
      initials: "SJ",
      avatarColor: "bg-emerald-600",
      segment: "standard",
      lifetimeValueEur: 2890,
      aiInfluencedRevenueEur: 945,
      recoveryCount: 0,
      vipRescueCount: 0,
      otaConversionCount: 0,
      lastAttribution: { kind: "ai_upsell", label: "ADR artışı", amountEur: 95, aiContributed: true },
      conversationId: "c4",
    },
  ],
  threads: [
    {
      id: "c1",
      guestName: "Ahmet Yılmaz",
      initials: "AY",
      avatarColor: "bg-violet-600",
      channel: "WhatsApp",
      language: "TR",
      status: "ai_active",
      lastMessage: "15-20 Temmuz arası çift kişilik odanız müsait mi?",
      time: "2 dk önce",
      unread: 2,
      revenueExposureEur: 0,
      attributions: [],
      flags: {
        ...DEFAULT_THREAD_FLAGS,
      },
    },
    {
      id: "c2",
      guestName: "Hans Mueller",
      initials: "HM",
      avatarColor: "bg-blue-600",
      channel: "WhatsApp",
      language: "DE",
      status: "ai_active",
      lastMessage: "I already tried the payment link twice. It keeps failing.",
      time: "6 dk önce",
      unread: 0,
      revenueExposureEur: 780,
      reservationId: "or2",
      guestId: "g2",
      attributions: [
        {
          kind: "payment_recovery",
          label: "Ödeme kurtarma €780 rezervasyonu korudu",
          amountEur: 780,
          aiContributed: true,
        },
      ],
      flags: {
        ...DEFAULT_THREAD_FLAGS,
        paymentRisk: true,
        recoveryActive: true,
        memoryAttached: true,
        priorRiskDetected: true,
      },
    },
    {
      id: "c3",
      guestName: "Elena Petrov",
      initials: "EP",
      avatarColor: "bg-rose-600",
      channel: "Instagram",
      language: "RU",
      status: "human_takeover",
      lastMessage: "Politika istisnası onaylandı — rezervasyon güvence altında",
      time: "12 dk önce",
      unread: 0,
      revenueExposureEur: 0,
      guestId: "g1",
      attributions: [
        {
          kind: "vip_intervention",
          label: "VIP müdahale iptal riskini önledi",
          amountEur: 2180,
          aiContributed: true,
        },
        {
          kind: "takeover_rescue",
          label: "Operatör devri rezervasyonu kurtardı",
          amountEur: 2180,
          aiContributed: false,
        },
      ],
      flags: {
        ...DEFAULT_THREAD_FLAGS,
        humanTakeover: true,
        vipEscalation: true,
        memoryAttached: true,
        vipHistory: true,
        priorRiskDetected: true,
      },
    },
    {
      id: "c4",
      guestName: "Sarah Johnson",
      initials: "SJ",
      avatarColor: "bg-emerald-600",
      channel: "Web",
      language: "EN",
      status: "resolved",
      lastMessage: "Ek satış paketi onaylandı — geç çıkış eklendi",
      time: "1 sa önce",
      unread: 0,
      revenueExposureEur: 0,
      reservationId: "or1",
      guestId: "g4",
      attributions: [
        {
          kind: "ai_upsell",
          label: "AI ek satış ADR'yi €95 artırdı",
          amountEur: 95,
          aiContributed: true,
        },
      ],
      flags: {
        ...DEFAULT_THREAD_FLAGS,
        memoryAttached: true,
        directBookingCandidate: true,
      },
    },
  ],
  alerts: [
    {
      id: "al1",
      title: "Ödeme sorunu tespit edildi",
      detail: "Hans Mueller · €780 · kurtarma devam ediyor",
      severity: "warning",
      timestamp: "6 dk önce",
      read: false,
      financialEur: 780,
      reservationId: "or2",
      guestLabel: "Hans Mueller",
      reason: "Ödeme sorunu — kurtarma başlatıldı",
      orchestrationStatus: "recovery_active",
      aiConfidence: 84,
      escalationLevel: "urgent",
      affectedSystems: ["revenue", "reservation", "recovery", "alert", "memory"],
    },
    {
      id: "al2",
      title: "VIP misafir — ekip devraldı",
      detail: "Elena Petrov · insan desteği tamamlandı · €2.180 güvence altında",
      severity: "success",
      timestamp: "12 dk önce",
      read: true,
      financialEur: 2180,
      guestLabel: "Elena Petrov",
    },
    {
      id: "al3",
      title: "OTA → direkt fırsat",
      detail: "Sophie Martin · direkt fiyat eşleştirmesi sürüyor",
      severity: "info",
      timestamp: "1 sa önce",
      read: true,
      guestLabel: "Sophie Martin",
    },
  ],
  aiActions: [
    {
      id: "ai1",
      action: "Ödeme kurtarma akışı başlatıldı",
      rationale: "€780 kart reddi — politika dahilinde alternatif bağlantı + depozito bölme.",
      timestamp: "11:25",
      financialImpactEur: 780,
      reservationId: "or2",
      conversationId: "c2",
    },
    {
      id: "ai2",
      action: "Operatör devri önerildi",
      rationale: "VIP politika sınırı · iptal olasılığı 0.88 · bağlam paketi hazırlandı.",
      timestamp: "08:42",
      financialImpactEur: 2180,
      conversationId: "c3",
    },
  ],
  auditEvents: [
    {
      id: "a1",
      action: "Ödeme kurtarma akışı başlatıldı",
      actor: "ai",
      rationale: "€780 kart reddi — politika dahilinde alternatif bağlantı + depozito bölme.",
      timestamp: "11:25",
      financialImpactEur: 780,
      attribution: "payment_recovery",
      reservationId: "or2",
    },
    {
      id: "a2",
      action: "Operatör devri önerildi",
      actor: "ai",
      rationale: "VIP politika sınırı · iptal olasılığı 0.88 · bağlam paketi hazırlandı.",
      timestamp: "08:42",
      financialImpactEur: 2180,
      attribution: "vip_intervention",
    },
    {
      id: "a3",
      action: "OTA → direkt dönüşüm akışı",
      actor: "ai",
      rationale: "Fiyat eşitliği teklifi — kapanışta %18 komisyon önleme.",
      timestamp: "09:04",
      financialImpactEur: 212,
      attribution: "ota_commission",
    },
    {
      id: "a4",
      action: "Kurtarma sonrası rezervasyon onaylandı",
      actor: "human",
      rationale: "Maria L. VIP istisnayı kapattı — AI bağlamı görüşmede korundu.",
      timestamp: "08:52",
      financialImpactEur: 2180,
      attribution: "takeover_rescue",
    },
    {
      id: "a5",
      action: "Ek satış paketi kabul edildi",
      actor: "ai",
      rationale: "Onay sonrası ADR artışı — geç çıkış + kahvaltı.",
      timestamp: "10:02",
      financialImpactEur: 95,
      attribution: "ai_upsell",
      reservationId: "or1",
    },
  ],
  operationsFeed: [
    {
      id: "f1",
      title: "Ödeme sorunu · kurtarma aktif",
      meta: "Hans Mueller · €780 · alternatif ödeme bağlantısı gönderildi",
      time: "6 dk önce",
      tone: "border-l-amber-400/70 bg-amber-500/[0.04]",
      financialEur: 780,
      eventType: "PAYMENT_FAILED",
    },
    {
      id: "f2",
      title: "VIP rezervasyon kurtarıldı",
      meta: "Elena Petrov · ekip devraldı · €2.180 güvence altında",
      time: "12 dk önce",
      tone: "border-l-emerald-400/65 bg-emerald-500/[0.04]",
      financialEur: 2180,
      eventType: "HUMAN_TAKEOVER",
    },
    {
      id: "f3",
      title: "OTA komisyonu tasarruf edildi",
      meta: "Sophie Martin · direkt rezervasyon · €212 tasarruf",
      time: "1 sa önce",
      tone: "border-l-violet-400/70 bg-violet-500/[0.04]",
      financialEur: 212,
      eventType: "OTA_CONVERSION",
    },
    {
      id: "f4",
      title: "Ek satış · ADR artışı",
      meta: "Sarah Johnson · onay sonrası +€95",
      time: "1 sa önce",
      tone: "border-l-blue-400/70 bg-blue-500/[0.04]",
      financialEur: 95,
      eventType: "UPSELL_ACCEPTED",
    },
  ],
  unifiedTimeline: SEED_UNIFIED_TIMELINE,
  lastPropagation: null,
  mutationPulseAt: null,
  lastEventAt: null,
};

export const INITIAL_OPERATIONAL_STATE: OperationalState = {
  ...(RAW_OPERATIONAL_STATE as OperationalState),
  guests: RAW_OPERATIONAL_STATE.guests.map((g) =>
    withGuestGraphDefaults(g as Parameters<typeof withGuestGraphDefaults>[0])
  ),
};
